name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: python:3.8

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t docker-image:latest .

    - name: Save Docker image as tar
      run: docker save -o docker-image.tar docker-image:latest

    - name: Upload Docker image
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: docker-image.tar
